import { NextResponse, type NextRequest } from "next/server";
import { createClient } from "@supabase/supabase-js";
import type Stripe from "stripe";
import { stripe } from "@/lib/stripe";
import type {
  InvoiceLineItem,
  InvoiceStatus,
  SubscriptionStatus,
} from "@/lib/types";

/**
 * Stripe webhook endpoint.
 *
 * Configure in Stripe dashboard → Developers → Webhooks:
 *   URL:     https://www.elmadigital.io/api/stripe/webhook
 *   Events:  invoice.*
 *            customer.subscription.*
 *            checkout.session.completed
 *
 * Local dev:  `stripe listen --forward-to localhost:3000/api/stripe/webhook`
 * That command prints the `whsec_...` secret to put in STRIPE_WEBHOOK_SECRET.
 *
 * Invoices created by us (admin one-offs, /reserve deposits) already have a
 * local row. Invoices generated by Stripe for a *subscription* do not — Stripe
 * creates them on its own billing schedule. So invoice handling upserts rather
 * than updates; an update-only handler silently drops every recurring invoice.
 */

const webhookSecret = process.env.STRIPE_WEBHOOK_SECRET;

// Service-role Supabase client — webhooks have no user session, so we
// bypass RLS for writes. Keys are server-only.
function supabaseService() {
  return createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}

type Supabase = ReturnType<typeof supabaseService>;

function mapStatus(s: Stripe.Invoice.Status | null | undefined): InvoiceStatus {
  switch (s) {
    case "draft":
      return "draft";
    case "open":
      return "open";
    case "paid":
      return "paid";
    case "uncollectible":
      return "uncollectible";
    case "void":
      return "void";
    default:
      return "draft";
  }
}

function mapSubscriptionStatus(
  s: Stripe.Subscription.Status | null | undefined
): SubscriptionStatus {
  switch (s) {
    case "incomplete":
    case "incomplete_expired":
    case "trialing":
    case "active":
    case "past_due":
    case "canceled":
    case "unpaid":
    case "paused":
      return s;
    default:
      return "incomplete";
  }
}

/** Stripe expands ids into objects depending on the call; normalize to an id. */
function idOf(
  ref: string | { id: string } | null | undefined
): string | null {
  if (!ref) return null;
  return typeof ref === "string" ? ref : ref.id;
}

function unixToIso(seconds: number | null | undefined): string | null {
  return seconds ? new Date(seconds * 1000).toISOString() : null;
}

/**
 * Stripe API 2025+ moved the invoice→subscription link off the top level.
 * It now lives at invoice.parent.subscription_details.subscription.
 */
function subscriptionIdFromInvoice(invoice: Stripe.Invoice): string | null {
  const details = invoice.parent?.subscription_details;
  return details ? idOf(details.subscription) : null;
}

/**
 * Stripe API 2025+ moved current_period_end off the subscription and onto each
 * subscription item. We bill single-item subscriptions, so the first item's
 * period is the subscription's period.
 */
function periodEndFromSubscription(sub: Stripe.Subscription): string | null {
  const item = sub.items?.data?.[0];
  return unixToIso(item?.current_period_end);
}

// ─── invoice.* ───────────────────────────────────────────────────────────────

async function handleInvoice(supabase: Supabase, invoice: Stripe.Invoice) {
  if (!invoice.id) {
    return { warning: "no invoice.id" };
  }

  const subscriptionId = subscriptionIdFromInvoice(invoice);
  const customerId = idOf(invoice.customer);

  const base = {
    status: mapStatus(invoice.status),
    stripe_hosted_invoice_url: invoice.hosted_invoice_url ?? null,
    stripe_invoice_pdf: invoice.invoice_pdf ?? null,
    stripe_subscription_id: subscriptionId,
    paid_at: unixToIso(invoice.status_transitions?.paid_at),
    sent_at: unixToIso(invoice.status_transitions?.finalized_at),
  };

  // Does a local row already exist? (admin-created one-off, or a recurring
  // invoice we've already mirrored on an earlier event)
  const { data: existing } = await supabase
    .from("invoices")
    .select("id")
    .eq("stripe_invoice_id", invoice.id)
    .maybeSingle();

  if (existing) {
    const updates: Record<string, unknown> = { ...base };
    // Don't null out timestamps we've already recorded.
    if (!base.paid_at) delete updates.paid_at;
    if (!base.sent_at) delete updates.sent_at;

    const { error } = await supabase
      .from("invoices")
      .update(updates)
      .eq("id", existing.id);
    if (error) throw new Error(error.message);

    return { action: "updated", local_invoice_id: existing.id };
  }

  // No local row — this is a Stripe-generated invoice (subscription renewal).
  // Resolve the client through the Stripe customer mapping.
  if (!customerId) {
    return { action: "skipped", reason: "no customer on invoice" };
  }

  const { data: client } = await supabase
    .from("clients")
    .select("id")
    .eq("stripe_customer_id", customerId)
    .maybeSingle();

  if (!client) {
    // Not a client we track (e.g. an invoice created directly in the Stripe
    // dashboard). Acknowledge so Stripe stops retrying.
    return { action: "skipped", reason: "no client for customer" };
  }

  // Link to the project the subscription is for, when we know it.
  let projectId: string | null = null;
  if (subscriptionId) {
    const { data: sub } = await supabase
      .from("subscriptions")
      .select("project_id")
      .eq("stripe_subscription_id", subscriptionId)
      .maybeSingle();
    projectId = sub?.project_id ?? null;
  }

  const lineItems: InvoiceLineItem[] = (invoice.lines?.data ?? []).map(
    (line) => ({
      description: line.description ?? "Subscription",
      amount_cents: line.amount ?? 0,
      quantity: line.quantity ?? 1,
    })
  );

  const { data: inserted, error } = await supabase
    .from("invoices")
    .insert({
      client_id: client.id,
      project_id: projectId,
      stripe_invoice_id: invoice.id,
      description: invoice.description ?? lineItems[0]?.description ?? null,
      line_items: lineItems,
      amount_total_cents: invoice.total ?? 0,
      currency: invoice.currency ?? "usd",
      due_date: invoice.due_date
        ? new Date(invoice.due_date * 1000).toISOString().slice(0, 10)
        : null,
      ...base,
    })
    .select("id")
    .single();

  if (error) throw new Error(error.message);

  return { action: "inserted", local_invoice_id: inserted.id };
}

// ─── customer.subscription.* ─────────────────────────────────────────────────

async function handleSubscription(
  supabase: Supabase,
  sub: Stripe.Subscription
) {
  const status = mapSubscriptionStatus(sub.status);

  const updates: Record<string, unknown> = {
    status,
    current_period_end: periodEndFromSubscription(sub),
    cancel_at_period_end: sub.cancel_at_period_end ?? false,
    canceled_at: unixToIso(sub.canceled_at),
    started_at: unixToIso(sub.start_date),
    stripe_price_id: idOf(sub.items?.data?.[0]?.price),
  };

  const { data: matched, error } = await supabase
    .from("subscriptions")
    .update(updates)
    .eq("stripe_subscription_id", sub.id)
    .select("id");

  if (error) throw new Error(error.message);

  if (!matched || matched.length === 0) {
    // Subscription exists in Stripe but not locally — created outside the
    // admin UI. Surface it rather than dropping it silently.
    console.warn(
      `[stripe webhook] no local subscription row for ${sub.id}; ignoring`
    );
    return { action: "skipped", reason: "no local subscription row" };
  }

  return { action: "updated", local_subscription_id: matched[0].id };
}

// ─── checkout.session.completed ──────────────────────────────────────────────

async function handleCheckoutCompleted(
  supabase: Supabase,
  session: Stripe.Checkout.Session
) {
  if (session.mode !== "subscription") {
    return { action: "ignored", reason: `mode=${session.mode}` };
  }

  const subscriptionId = idOf(session.subscription);
  if (!subscriptionId) {
    return { action: "skipped", reason: "no subscription on session" };
  }

  // Pull the full subscription so we can record price + period in one write.
  const sub = await stripe.subscriptions.retrieve(subscriptionId);

  const { data: matched, error } = await supabase
    .from("subscriptions")
    .update({
      stripe_subscription_id: sub.id,
      stripe_price_id: idOf(sub.items?.data?.[0]?.price),
      status: mapSubscriptionStatus(sub.status),
      current_period_end: periodEndFromSubscription(sub),
      cancel_at_period_end: sub.cancel_at_period_end ?? false,
      started_at: unixToIso(sub.start_date),
      checkout_url: null, // link is spent
    })
    .eq("stripe_checkout_session_id", session.id)
    .select("id");

  if (error) throw new Error(error.message);

  if (!matched || matched.length === 0) {
    return { action: "skipped", reason: "no local row for checkout session" };
  }

  // Make sure the customer id is on the client so future invoices resolve.
  const customerId = idOf(session.customer);
  if (customerId) {
    const { data: row } = await supabase
      .from("subscriptions")
      .select("client_id")
      .eq("id", matched[0].id)
      .single();
    if (row) {
      await supabase
        .from("clients")
        .update({ stripe_customer_id: customerId })
        .eq("id", row.client_id)
        .is("stripe_customer_id", null);
    }
  }

  return { action: "linked", local_subscription_id: matched[0].id };
}

// ─── Route ───────────────────────────────────────────────────────────────────

export async function POST(req: NextRequest) {
  if (!webhookSecret) {
    console.error("[stripe webhook] STRIPE_WEBHOOK_SECRET is not set");
    return NextResponse.json(
      { error: "Webhook secret not configured" },
      { status: 500 }
    );
  }

  const signature = req.headers.get("stripe-signature");
  if (!signature) {
    return NextResponse.json({ error: "Missing signature" }, { status: 400 });
  }

  // Stripe signs the raw bytes. Do NOT use req.json() here.
  const rawBody = await req.text();

  let event: Stripe.Event;
  try {
    event = stripe.webhooks.constructEvent(rawBody, signature, webhookSecret);
  } catch (err) {
    const message = err instanceof Error ? err.message : "unknown";
    console.error("[stripe webhook] signature verification failed:", message);
    return NextResponse.json(
      { error: `Signature verification failed: ${message}` },
      { status: 400 }
    );
  }

  const supabase = supabaseService();

  try {
    let result: Record<string, unknown>;

    if (event.type.startsWith("invoice.")) {
      result = await handleInvoice(
        supabase,
        event.data.object as Stripe.Invoice
      );
    } else if (event.type.startsWith("customer.subscription.")) {
      result = await handleSubscription(
        supabase,
        event.data.object as Stripe.Subscription
      );
    } else if (event.type === "checkout.session.completed") {
      result = await handleCheckoutCompleted(
        supabase,
        event.data.object as Stripe.Checkout.Session
      );
    } else {
      return NextResponse.json({ received: true, ignored: event.type });
    }

    return NextResponse.json({ received: true, event: event.type, ...result });
  } catch (err) {
    const message = err instanceof Error ? err.message : "unknown";
    console.error(`[stripe webhook] ${event.type} failed:`, message);
    // 500 tells Stripe to retry — correct for a transient DB failure.
    return NextResponse.json({ error: message }, { status: 500 });
  }
}

// Explicitly reject GET so someone hitting the URL in a browser gets a clean 405
// instead of a generic Next.js 404/500.
export async function GET() {
  return NextResponse.json(
    { error: "Method not allowed — POST only" },
    { status: 405 }
  );
}
